version: '3.3'

services:
  app:
    build:
      context: .
    ports:
      - 8000:8000
    volumes:
      - ./app:/app

    environment:
      - SECRET_KEY=devsecretkey
      - DEBUG=1
    
    depends_on:
      - db
  db:
    image: postgis/postgis:13-master
    environment:
      - POSTGRES_DB=geodb
      - POSTGRES_USER=pasoriano
      - POSTGRES_PASSWORD=mayte2022
